### ISSUE TITLE
Testing with Exq

### ISSUE THREAD

**Issue by hwhelchel** [akira/exq#199]
- Fake Redis: Sidekiq has an [in memory fake queue](https://github.com/mperham/sidekiq/wiki/Testing#testing-worker-queueing-fake) that can be used for testing. It also allows for immediate running of jobs inline. Does exq have any similar testing functionality? Right now I can see the jobs going all the way through to redis and then I'm getting three errors in my test output. The jobs require reading data from the DB and the data isn't showing up. I think but am not sure this is because the foreground tests run in a sandboxed DB transaction.

I dug into this some more and found this [article](https://medium.com/@qertoip/making-sense-of-ecto-2-sql-sandbox-and-connection-ownership-modes-b45c5337c6b7#.fqfafo1bp) and [elixir issue](https://github.com/elixir-ecto/ecto/issues/1319)

I changed `Ecto.Adapters.SQL.Sandbox.mode(Arches.Repo, :manual)` to `Ecto.Adapters.SQL.Sandbox.mode(Arches.Repo, {:shared, self()})` which stopped error 1 and 3. But makes me confused because if `:shared` enables child processes to share parent connection and transaction then shouldn't Error 2 stop as well--the worker should be able to see the record in the DB?

Error 1:

```
10:55:44.325 [error] GenServer Exq terminating
** (stop) exited in: GenServer.call(Exq.Worker.Sup, {:start_child, ["{\"queue\":\"default\",\"jid\":\"ebae2772-86c9-4f94-b7af-f300c196df77\",\"enqueued_at\":1467989698.60931,\"class\":\"Arches.AnswerHandler\",\"args\":[\"18X86fmtfj9uvT7sWafKri2s3aa4RXxyQU\",2638,1567],\"retry\":true}", #PID<0.300.0>, "default", 872496, Exq.Stats, "exq", "Hoyts-MacBook-Air", Exq.Redis.Client, Exq.Middleware.Server]}, :infinity)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
    (exq) lib/exq/manager/server.ex:269: Exq.Manager.Server.dispatch_job/3
    (exq) lib/exq/manager/server.ex:262: Exq.Manager.Server.dispatch_job/2
    (elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
    (exq) lib/exq/manager/server.ex:229: anonymous fn/2 in Exq.Manager.Server.dequeue_and_dispatch/2
    (exq) lib/exq/manager/server.ex:322: Exq.Manager.Server.rescue_timeout/2
    (exq) lib/exq/manager/server.ex:205: Exq.Manager.Server.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
```

Error 2

``` elixir
  # Run in BG Job to confirm no users present
  IO.inspect("IN BG JOB")
  IO.inspect(Repo.all User)
```

```
"IN BG JOB"
[]
10:55:44.935 [error] Process #PID<0.345.0> raised an exception
** (Ecto.NoResultsError) expected at least one result but got none in query:

from u in Arches.User,
  where: u.id == ^2637

    (ecto) lib/ecto/repo/queryable.ex:74: Ecto.Repo.Queryable.one!/4
    (arches) web/workers/inbound_message_handler.ex:11: Arches.InboundMessageHandler.perform/2
    (exq) lib/exq/worker/server.ex:115: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2
```

Error 3

```
10:55:45.507 [error] Process #PID<0.388.0> raised an exception
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.388.0>.

When using ownership, you must manage connections in one
of the three ways:

  * By explicitly checking out a connection
  * By explicitly allowing a spawned process
  * By running the pool in shared mode

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (db_connection) lib/db_connection.ex:722: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:623: DBConnection.run/3
    (db_connection) lib/db_connection.ex:517: DBConnection.execute/4
    (ecto) lib/ecto/adapters/sql.ex:228: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:410: Ecto.Adapters.SQL.sql_call!/6
    (ecto) lib/ecto/adapters/sql.ex:394: Ecto.Adapters.SQL.execute/6
    (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
```
- Testing to ensure job was enqueued: I'm pattern matching on the queue to look for the jobs I expect to have been enqueued. Is there a cleaner api to do this?

``` elixir
it "enqueues a SubscriptionCreate job" do
  action(:create, params)
  {:ok, [%Exq.Support.Job{class: class}]} = Exq.Api.jobs(Exq.Api, "default")

  expect(class).to eq("Arches.SubscriptionCreate")
end
```

Once we figure out some best practices I'd be happy to add what we learn to the documentation.

**Comment by akira** [comment]
For replicating the issues, do you happen to have your repo accessible?

**Comment by akira** [comment]
@hwhelchel Can you try against latest master? Wondering any of these errors are fixed on latest.

**Comment by luki3k5** [comment]
Hi, we are seeing the third error happening as well for us on our project.

We tried different method of sharing, checking out or allowing connection but it does not help we still see this: 

```
    (db_connection) lib/db_connection.ex:718: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:619: DBConnection.run/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:78: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:424: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:72: Ecto.Repo.Queryable.one!/4
    (loopnext) lib/loopnext/workers/snapshot_survey_worker.ex:18: Loopnext.Workers.SnapshotSurveyWorker.perform/2
    (exq) lib/exq/worker/server.ex:119: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2
17:20:19.425 [error] Process #PID<0.1178.0> raised an exception
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.1178.0>.

When using ownership, you must manage connections in one
of the three ways:

  * By explicitly checking out a connection
  * By explicitly allowing a spawned process
  * By running the pool in shared mode

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (db_connection) lib/db_connection.ex:718: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:619: DBConnection.run/3
    (db_connection) lib/db_connection.ex:463: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:78: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:235: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:424: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/repo/queryable.ex:72: Ecto.Repo.Queryable.one!/4
    (loopnext) lib/loopnext/workers/snapshot_survey_worker.ex:18: Loopnext.Workers.SnapshotSurveyWorker.perform/2
    (exq) lib/exq/worker/server.ex:119: anonymous fn/3 in Exq.Worker.Server.dispatch_work/2
.
```

**Comment by akira** [comment]
@luki3k5 is this with Ecto 2, and tests that run concurrently?  You may need to use manual mode.  

See:
https://github.com/elixir-ecto/ecto/blob/v2.0.0/CHANGELOG.md#concurrent-transactional-tests
http://www.cultivatehq.com/posts/using-ecto-2-without-phoenix-but-with-tests/

If this doesn't work, let me know exact version of all your libraries (Phoenix, Ecto, etc), and if you have a repo I can look at that is failing then even better.

**Comment by diegonogueira** [comment]
I have the same problem.. 
For now, I'm using this workaround:

```elixir
  def enqueue_feed(worker, args) do
    if Mix.env == :test do
      apply(worker, :perform, args)
    else
      Exq.enqueue(Exq, "feeds", worker, args)
    end
  end
```

**Comment by hwhelchel** [comment]
Sorry to be unresponsive on this. I've put down my phoenix project, and haven't had time to look into these issues further.

**Comment by akira** [comment]
Given this is a need, I will take a look at providing a test interface with a fake queue.

**Comment by lbighetti** [comment]
I'm having this issue also. Using @diegonogueira workaround for now, but a test interface with would be great @akira.

**Comment by egeersoz** [comment]
Yes, a test interface would be great. Right now we're having to do `if Mix.env != :test do` inside our worker functions, which adds a lot of clutter.

**Comment by sb8244** [comment]
I may end up looking into a test interface here in my free time. @akira have you thought about this at all since the issue started?

For those that come onto this later: another thing that can be useful is something like Mockery to do a swap out of the implementation in an easy to test way.

```
defmodule My.Worker.Example do
  def enqueue(item) do
    Exq.enqueue(Exq, "default", __MODULE__, [item.id])
  end

  def perform(item_id) do
    IO.inspect item_id
  end
end
```

In this case, if my application calls `My.Worker.Example.enqueue(item)`, I can put that module behind mockery and assert it's called correctly.

**Comment by sb8244** [comment]
It's probably also worth mentioning. I'm utilizing explicit startup in my application and have it disabled if the env is test. This means that any enqueued job will fail the test it's in, which makes it easy for 0 things to slip through.

**Comment by klacointe** [comment]
@akira Any news on this issues?

**Comment by akira** [comment]
@sb8244 @klacointe I don't have bandwidth to implement this at the moment. However, I would accept a PR and could review it, and also provide feedback for any ideas.

**Comment by sergey-chechaev** [comment]
@hwhelchel @diegonogueira Use [Mock](https://github.com/jjh42/mock):
```
test "test something" do
   with_mock Exq, enqueue_in: fn _, _, _, _, _ -> {:ok, "id"} end do
       {:ok, _user} = UserCreator.call("bla", "bla")
       assert called(
       Exq.enqueue_in(Exq, "default", 86_400, BlaJob, [user.id])
     )
   end
end
```

**Comment by bgentry** [comment]
Mock is not a good solution because it requires you to disable async for the entire test file it’s being used in. Using it in more than a couple of test files can massively slow down a test suite.

**Comment by ananthakumaran** [comment]
We have merged PR https://github.com/akira/exq/pull/396 which adds support for testing. Please give it a try and report any issues. I am closing this issue as the main problem is addressed.

**Comment by sinakarimi** [comment]
@ananthakumaran is there any indication when #396 might be released to Hex? We're currently using a git ref but we'd like to avoid doing this as soon as possible.

**Comment by ananthakumaran** [comment]
ping @akira

**Comment by akira** [comment]
Thanks, I will release this as soon as I get a chance.

**Comment by akira** [comment]
This is now released @ananthakumaran @sinakarimi
